<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SampleService.A</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicConfig.Library\DynamicConfig.Library.csproj" />
  </ItemGroup>

</Project>
